name: license_checker_for_github_action
description: A script to show licences of dependencies that can be used in github actions. Forked from dart_license_checker.
version: 0.0.2
homepage: https://github.com/Techspired/license_checker_for_github_action

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.7.0
  pana: ^0.21.7
  pubspec_parse: ^1.2.0
  barbecue: ^0.4.0
  nm: ^0.5.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  dart_license_checker: dart_license_checker
